package org.cip4.tools.jdfeditor.controller;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.cip4.tools.jdfeditor.App;
import org.cip4.tools.jdfeditor.service.SettingService;
import org.cip4.tools.jdfeditor.view.MainView;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URI;

/**
 * The Main Controller class.
 */
public class MainController implements ActionListener {

    private static final Logger LOGGER = LogManager.getLogger(MainController.class.getName());

    public static final String ACTION_ONLINE_HELP = "actionOnlineHelp";

    public static final String ACTION_INFO = "actionInfo";

    private final SettingService settingService = new SettingService();

    private final MainView mainView;

    private File file;

    /**
     * Default constructor.
     */
    public MainController() {
        this(null);
    }

    /**
     * Custom constructor. Accepting a file object for initializing.
     * @param file The JDF File which should be shown after start.
     */
    public MainController(File file) {

        this.mainView = new MainView();
        this.mainView.registerController(this);
        this.file = file;
    }

    /**
     * Display the main form.
     */
    public void displayForm() {

        mainView.display(file);
    }


    /**
     * ActionListner for defined actions.
     * @param e The ActionEvent generated by the calling object.
     */
    @Override
    public void actionPerformed(ActionEvent e) {


        switch (e.getActionCommand()) {

            case ACTION_ONLINE_HELP:
                openOnlineHelp();
                break;

            case ACTION_INFO:
                showInfo();
                break;

            default:
                LOGGER.warn(String.format("ActionCommnd '%s' is unknown.", e.getActionCommand()));
                break;
        }
    }

    /**
     * Open the JDF Editor online help or if not possible show a message box with the URL.
     */
    private void openOnlineHelp() {

        LOGGER.info("Display Online Help.");

        // define url
        String url = "http://cip4.org/jdfeditor";

        // open in browser (if possible)
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI(url));

            } catch (Exception ex) {
                LOGGER.error("Error opening Online Help.", ex);
            }
        } else {
            String msg = "see " + url;
            String title = "Online Help";

            mainView.showMessageDialog(msg, title);
        }
    }

    /**
     * Show JDF Editor Info Dialog.
     */
    private void showInfo() {

        LOGGER.info("Show Info Window.");

        String msg = App.APP_NAME + "\n" + App.APP_VERSION + " (" + App.APP_RELEASE_DATE + ")";
        String title = "Version";

        mainView.showMessageDialog(msg, title);
    }
}
