
name: Test

on:
  push:
    branches-ignore: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: macos-latest
    steps:
      -   name: Setup JDK 8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

      -   name: Check out sources...
          uses: actions/checkout@v2

      -   name: Build with Gradle
          run: ./gradlew test

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew test

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew test
