name: Release

on:
  push:
    branches:
      - macos-build
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Tooling
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createApp

      - name: Sign & Notarize
        run: gon .github/workflows/macos/gon-config.json

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/macApp/JDFEditor.app
            JDFEditor.dmg