name: Test Signing on Windows

on:
  workflow_dispatch:
  push:
    branches: [ sign-windows ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 15
          check-latest: true

      - name: Check out sources...
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew --no-daemon jpackage

      - name: Rename binaries
        run: mv build/jpackage/JDFEditor*.msi build/jpackage/JDFEditor-SNAPSHOT-${{ github.run_number }}.msi

      - name: Store certificate
        id: certificate
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'build_certificate.pfx'
          encodedString: ${{ secrets.CODE_SIGN_CERTIFICATE }}

      - name: Sign MSI
        env:
          BUILD_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGN_PASSWORD }}
          CERTIFICATE_SHA1: ${{ secrets.CODE_SIGN_SHA1 }}
        run: |
          signtool.exe --% sign /f ${{ steps.certificate.outputs.filePath }} /sha1 $env:CERTIFICATE_SHA1 /d "Installer for JDFEitor" /p $env:BUILD_CERTIFICATE_PASSWORD /v /fd SHA256 /tr "http://timestamp.digicert.com/" /td SHA256 build/jpackage/JDFEditor-SNAPSHOT-${{ github.run_number }}.msi

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/jpackage/JDFEditor-SNAPSHOT-*.msi