name: Snapshot

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  call-tool-snapshot:
    name: 🏭
    uses: cip4/.github/.github/workflows/tool-snapshot.yml@master
    with:
      java-version: 15
      java-distribution: 'adopt'
      confluence-label: jdfeditor
      confluence-content-id: 1457553961
      apple-bundle-id: org.cip4.jdfeditor
    secrets: inherit